version: '3.8'

services:
  api-converter:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=development

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
